### ISSUE TITLE
クリックしたときに上塗りされる処理の削除

### ISSUE THREAD

**Issue by jagio0129** [jagio0129/atack25#6]
同色で挟むと挟まれたパネルの色が上塗りされる機能(めんどいので以降"リンク機能")が実装されたので、クリック時に上塗りする処理は不要になった(灰色を除く)

理由としては以下
- 誤操作で違う回答者のパネルを上塗りすると訳が分からなくなるのでそれを防ぐため
- 灰色は、クリックミスった時の消しごみの役割を果たすので上塗り処理は必要

**Comment by ghost** [comment]
アタックチャンスで上塗りするときは、灰色でいったん消して塗る感じですかね。
確かに誤操作の対策は必要そうですね。上塗りできなくしても、間違って別の場所を塗ってしまって多数のパネルが反転した時グダりそうです。undo機能をつけるか。現地の誰かが毎回スクショ取るとかですかね？
