### ISSUE TITLE
ちょっと危険だと思った仕様(最初にpanelをクリックすることによる不具合)

### ISSUE THREAD

**Issue by ghost** [jagio0129/atack25#8]
select_panelをクリックせずにpanelをクリックすると塗れない&他の色で囲むと塗られるpanelができる。

**Comment by UNILORN** [comment]
> 対策

- 初期値を設定（灰色） 

こちら @fcfcqloow お願いします

**Comment by ghost** [comment]
ちなみに
灰色を選んでクリックすると
`<td id="13" class="panel">13</td>`
から
`<td id="13" class="panel" style="background-color: rgb(172, 172, 172);">13</td>`
のようになりますが
最初から後者にしていても解決しませんでした(フロントエンドなんもわからんので的外れなこといってるかも)

**Comment by ghost** [comment]
一度でもselect_panelをクリックするとこの問題は起きません
いや、起きてたかも。
とにかくこの変なpanelがなぜできるのか調べてほしいです。。。(私も時間があったら調べます)
(追記)たぶん最初に該当panelをクリックしてしまってた

**Comment by UNILORN** [comment]
https://github.com/jagio0129/atack25/blob/master/index.html#L102

ここの値を初期値 `5` に変更すれば解決すると思います

**Comment by ghost** [comment]
手元で試してみるとたしかにそれでうまくいきました！

**Comment by fcfcqloow** [comment]
```
this.state = GRAY
```
を追加して解決しました。
